Move to single Activity architecture
codequest-eu/devstarter-android-mvi pull request #14
Opened 2021-01-11 13:47 UTC by braczkow

As discussed: I have refactored the devstarter to a single-activity architecture.
One discussable point: I have removed BaseActivity (as we have only one either way!). 

If anyone has a problem with this, I can revert this change.

2021-01-11 14:05 UTC, krzdabrowski approved these changes

2021-01-11 14:05 UTC, krzdabrowski commented on app/src/main/res/layout/activity_main.xml
> +<FrameLayout
You could also consider [FragmentContainerView](https://developer.android.com/reference/androidx/fragment/app/FragmentContainerView) :)

2021-01-11 14:05 UTC, krzdabrowski commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
Is it really necessary? I've never really used that and thought that `androidx.appcompat:appcompat` includes all necessary "legacy" classes.

2021-01-11 14:34 UTC, krzdabrowski approved these changes

2021-01-12 07:51 UTC, MDikkii requested changes

2021-01-12 07:52 UTC, braczkow commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
Removed, closing.

2021-01-12 07:53 UTC, braczkow commented on app/src/main/java/com/example/appName/data/repository/exampleuser/LocalExampleUserRepository.kt
>  import io.reactivex.rxjava3.schedulers.Schedulers
done

2021-01-12 07:54 UTC, braczkow commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
done

2021-01-12 07:54 UTC, braczkow commented on app/src/main/java/com/example/appName/presentation/features/main/MainFragment.kt
> +}
done

2021-01-12 07:54 UTC, braczkow commented on app/src/test/java/com/example/appName/utils/TestSchedulersFactory.kt
> +}
done

2021-01-12 09:11 UTC, braczkow commented on app/src/main/res/layout/activity_main.xml
> +<FrameLayout
done

2021-01-12 09:11 UTC, braczkow commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
Removed, done.

2021-01-12 09:12 UTC, braczkow commented on app/src/main/java/com/example/appName/data/repository/exampleuser/LocalExampleUserRepository.kt
>  import io.reactivex.rxjava3.schedulers.Schedulers
done

2021-01-12 09:12 UTC, braczkow commented on app/src/test/java/com/example/appName/presentation/features/main/MainPresenterTest.kt
> +
I'm planning some UT-refinement task, so I'd leave it for now

2021-01-12 09:20 UTC, MDikkii approved these changes

2021-01-12 09:25 UTC, merged