Implement viewEvents by UnicastWorkSubject. Switch back to Rx for vie…
codequest-eu/devstarter-android-mvi pull request #15
Opened 2021-01-12 20:04 UTC by braczkow

2021-01-12 20:05 UTC, braczkow commented on app/src/main/java/com/example/appName/presentation/features/main/MainPresenter.kt
> +        if ((0..1).random() == 1) {
Please note that this randomness will be replaced by some real-network communication when some features are added. For now it's a demo of "emit event, no viewState update" scenario

2021-01-12 20:05 UTC, braczkow commented on app/src/main/java/com/example/appName/presentation/features/base/BasePresenter.kt
> +abstract class BasePresenter<VIEW_STATE : Serializable, PARTIAL_VIEW_STATE, INTENT, VIEW_EVENT>(
Afterthoughts: VIEW_EVENT should be moved to be the 2nd parameter

2021-01-13 07:54 UTC, krzdabrowski reviewed
Looking good, I added small suggestions for improvement. I guess someone else should take a look on that as well 😉

2021-01-13 07:54 UTC, krzdabrowski commented on app/src/main/java/com/example/appName/presentation/features/base/BaseFragment.kt
>      override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
This method currently doesn't do anything (as `bind` is empty) so I think it's safe to remove? 🙂

2021-01-13 07:54 UTC, krzdabrowski commented on app/src/main/java/com/example/appName/presentation/features/base/BasePresenter.kt
>          super.onCleared()
Just a side note - you don't need to call `super.onCleared()` as this function in `ViewModelX` is empty 🙂

2021-01-13 07:54 UTC, krzdabrowski commented on app/src/main/java/com/example/appName/presentation/features/base/BasePresenter.kt
> +    private val viewEventsSubject: UnicastWorkSubject<VIEW_EVENT> = UnicastWorkSubject.create()
You could move these Observables to others `val`s on top of a file, to preserve clarity

2021-01-13 07:54 UTC, krzdabrowski commented on app/src/main/java/com/example/appName/presentation/features/main/MainViewState.kt
> +sealed class MainEvent {
I'm not sure if MainEvent should be in MainViewState file ultimatelly - it wasn't my first thought when I was looking for this class 🙂
Maybe consider extracting it (or renaming this file)? It's just a suggestion, keeping in mind that this distribution should scale properly later.

2021-01-13 07:54 UTC, krzdabrowski commented on app/src/main/res/layout/activity_main.xml
> +<androidx.fragment.app.FragmentContainerView android:id="@+id/main_frame"
Taking into account that in Metronome and Snopsis projects I see `camelCase` as a naming convention for Views in XMLs, I suggest keeping that as well in DevStarter 🙂

2021-01-13 08:19 UTC, braczkow commented on app/src/main/res/layout/activity_main.xml
> +<androidx.fragment.app.FragmentContainerView android:id="@+id/main_frame"
Whole devstarter uses `snake_case`; personally I like it, as you immediately know some xml-originating entity is referenced. Let's discuss with complete #robociki :)

2021-01-13 08:31 UTC, braczkow commented on app/src/main/java/com/example/appName/presentation/features/base/BasePresenter.kt
>          super.onCleared()
done

2021-01-13 08:33 UTC, braczkow commented on app/src/main/java/com/example/appName/presentation/features/base/BaseFragment.kt
>      override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
Removed for now. I think something similar will be introduced once we migrate to ViewBinding, as `kotlinx.android.synthetic` is deprecated

2021-01-13 08:56 UTC, braczkow commented on app/src/main/java/com/example/appName/presentation/features/main/MainViewState.kt
> +sealed class MainEvent {
Personally I like grouping several related classes together. I'd go with something like:
```
class MainScreen {
   class ViewState
   class ViewEvent
   class Intent
   class PartialState
}
```

Imo it's easier to use, as you always type `MainScreen.`..

BUT: that's clearly a personal-taste issue, and team is accustomed to class-per-file conventions, so I'll go with that.

2021-01-13 08:57 UTC, braczkow commented on app/src/main/java/com/example/appName/presentation/features/main/MainViewState.kt
> +sealed class MainEvent {
done

2021-01-13 09:00 UTC, braczkow commented on app/src/main/java/com/example/appName/presentation/features/base/BasePresenter.kt
> +    private val viewEventsSubject: UnicastWorkSubject<VIEW_EVENT> = UnicastWorkSubject.create()
done

2021-01-13 09:03 UTC, braczkow commented on app/src/main/res/layout/activity_main.xml
> +<androidx.fragment.app.FragmentContainerView android:id="@+id/main_frame"
OK, changed my mind, it's a nice idea.

2021-01-13 09:13 UTC, braczkow commented on app/src/main/res/layout/activity_main.xml
> +<androidx.fragment.app.FragmentContainerView android:id="@+id/main_frame"
@krzdabrowski I close this for now, I'll refactor it with subsequent PR

2021-01-13 09:56 UTC, krzdabrowski approved these changes

2021-01-13 15:25 UTC, kubak89 requested changes
Some stylistic nits, and one functional change.

2021-01-13 15:25 UTC, kubak89 commented on app/src/test/java/com/example/appName/presentation/features/base/BasePresenterTest.kt
> +class BasePresenterTest {
Nit, but I'd prefer if `BasePresenterTest` class was the first class declared in `BasePresenterTest.kt` file.

2021-01-13 15:25 UTC, kubak89 commented on app/src/main/java/com/example/appName/presentation/features/base/BaseFragment.kt
> +abstract class BaseFragment<VIEW_STATE : Serializable, VIEW_EVENT, PRESENTER : BasePresenter<VIEW_STATE, *, *, VIEW_EVENT>>(
It's not really in a scope of the current PR, but in future - could we extract MVI's view functionality to a base Android-agnostic class? Check https://github.com/codequest-eu/snopsis-android/blob/develop/app/src/main/java/com/pathbysimplex/presentation/features/base/BaseView.kt to see what I mean.

2021-01-13 15:25 UTC, kubak89 commented on app/src/main/java/com/example/appName/presentation/features/base/BasePresenter.kt
> +    val viewEvents: Observable<VIEW_EVENT> get() = viewEventsSubject
Nit, but could we keep the ordering of private and public fields consistent?

2021-01-13 15:25 UTC, kubak89 commented on app/src/main/java/com/example/appName/presentation/features/base/BaseFragment.kt
> +                .observeOn(SchedulersFactory.main)
Please add `distinctUntilChanged` operator here to avoid rendering duplicate view states, as sometimes accepting intents only result in interactions with data layer without causing changes to view state.

2021-01-13 15:36 UTC, braczkow commented on app/src/main/java/com/example/appName/presentation/features/base/BaseFragment.kt
> +abstract class BaseFragment<VIEW_STATE : Serializable, VIEW_EVENT, PRESENTER : BasePresenter<VIEW_STATE, *, *, VIEW_EVENT>>(
For sure we lack some abstraction of the View, so this could be a welcome change

2021-01-13 15:48 UTC, braczkow commented on app/src/main/java/com/example/appName/presentation/features/base/BasePresenter.kt
> +    val viewEvents: Observable<VIEW_EVENT> get() = viewEventsSubject
But do you mean:
a)
```
    private val viewStateSubject: BehaviorSubject<VIEW_STATE> = BehaviorSubject.create()
    val viewState: Observable<VIEW_STATE> get() = viewStateSubject

    private val viewEventsSubject: UnicastWorkSubject<VIEW_EVENT> = UnicastWorkSubject.create()
    val viewEvents: Observable<VIEW_EVENT> get() = viewEventsSubject
```

or b)
```
    private val viewStateSubject: BehaviorSubject<VIEW_STATE> = BehaviorSubject.create()
    private val viewEventsSubject: UnicastWorkSubject<VIEW_EVENT> = UnicastWorkSubject.create()

    val viewState: Observable<VIEW_STATE> get() = viewStateSubject
    val viewEvents: Observable<VIEW_EVENT> get() = viewEventsSubject
```

2021-01-13 16:04 UTC, braczkow commented on app/src/main/java/com/example/appName/presentation/features/base/BaseFragment.kt
> +                .observeOn(SchedulersFactory.main)
done

2021-01-13 16:05 UTC, braczkow commented on app/src/main/java/com/example/appName/presentation/features/base/BaseFragment.kt
> +abstract class BaseFragment<VIEW_STATE : Serializable, VIEW_EVENT, PRESENTER : BasePresenter<VIEW_STATE, *, *, VIEW_EVENT>>(
https://github.com/codequest-eu/devstarter-android-mvi/issues/18
created, resolving this comment

2021-01-13 16:05 UTC, braczkow commented on app/src/test/java/com/example/appName/presentation/features/base/BasePresenterTest.kt
> +class BasePresenterTest {
done

2021-01-13 16:32 UTC, braczkow commented on app/src/main/java/com/example/appName/presentation/features/base/BasePresenter.kt
> +    val viewEvents: Observable<VIEW_EVENT> get() = viewEventsSubject
As this is a 'nit', I go with (a)

2021-01-14 10:59 UTC, kubak89 approved these changes

2021-01-14 11:34 UTC, merged