Multi module + navigation
codequest-eu/devstarter-android-mvi pull request #19
Opened 2021-01-14 16:06 UTC by braczkow

Hi, 2 things at once, but they are tightly coupled, so:
#### multi-module:
I have created a simple multi-module architecture, similar to what we've discussed:
base - features - app
ATM there are 2 features: _user_ and _home_. 
No cross-feature dependencies - App is stil too simple for that.

One **important** note: I have extracted the dependencies into _deps.gradle_ and _deps-test.gradle_. I have tried to make them available from within the _base_ module, but it a) is problematic when using Hilt (you have to include dagger deps in any module either way), b) does not work for test dependencies. My solution has one flaw: AS no longer highlights in yellow outdated deps. It has to be addressed otherwise, like ./gradlew dependenciesUpdates 

Other **important** note: I have moved all resources to base module, except for layouts. Maybe we could even move them all (?)

I have also extracted common plugins declarations into _plugs.gradle_

#### navigation:
I have added the foundation for Navigation handling: 
`base.nav` contains `Navigation` interface, which contains `Direction` sealed class. 
`app.nav` contains `NavigationImpl` which implements the interface by the means of _jetpack navigation_. 

(this way we avoid circular dependencies)

It's quite simple and works nice; also Hilt plays nicely here. If any App would need some more advanced features (nested graphs, feature-originating graphs), it should be possible to incorporate it without a problem.

I'm not sure if we should add 'SafeArgs': see HomeFragment.bundle for a solution that works nice without it.

2021-01-15 06:57 UTC, przemek19980102 commented on app/src/main/res/navigation/nav_graph.xml
> +        android:id="@+id/login_fragment"
I don't like that ID's of fragments are not referring to their class name somehow. This should be `main_fragment` probably to be more self explainatory

2021-01-15 06:57 UTC, przemek19980102 commented on app/src/main/res/navigation/nav_graph.xml
> +        android:id="@+id/demo_fragment"
I don't like that ID's of fragments are not referring to their class name somehow. This should be `home_fragment` probably to be more self explainatory

2021-01-15 07:01 UTC, przemek19980102 commented on base/src/main/java/com/example/base/nav/Navigation.kt
> +        data class toHomeScreen(val text: String): Direction()
I think we pass a resource here anyway, can't we mark it with sth like `@StringRes` or an equivalent one to the value expected?

2021-01-15 07:03 UTC, przemek19980102 commented on home/src/main/java/com/example/home/HomeFragment.kt
> +        const val TEXT_ARG = "TEXT_ARG"
could be private I think

2021-01-15 08:29 UTC, braczkow commented on home/src/main/java/com/example/home/HomeFragment.kt
> +        const val TEXT_ARG = "TEXT_ARG"
done

2021-01-15 08:29 UTC, braczkow commented on app/src/main/res/navigation/nav_graph.xml
> +        android:id="@+id/demo_fragment"
I have aligned all names between xmls and code, thanks!

2021-01-15 08:30 UTC, braczkow commented on app/src/main/res/navigation/nav_graph.xml
> +        android:id="@+id/login_fragment"
It's missed-in-refactoring, aligned. thanks!

2021-01-15 08:32 UTC, krzdabrowski requested changes
And one side note as I cannot comment in proper place - I'm not sure if we should _move_ all resources to `base` module. After all, there will be probably both `colours`/`strings` in Base and App modules because there would be cases in real-world apps that you cannot handle everything in Base.

2021-01-15 08:32 UTC, krzdabrowski commented on app/src/main/java/com/example/appName/nav/NavigationModule.kt
> +@InstallIn(FragmentComponent::class)
I'm not that sure if NavigationModule should be scoped to `Fragment` lifecycle 🙂

2021-01-15 08:32 UTC, krzdabrowski commented on app/src/main/res/layout/activity_main.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
I don't think this nesting is necessary - `FragmentContainerView` extends `FrameLayout` and works fine as a top-level container in XMLs 🙂

2021-01-15 08:32 UTC, krzdabrowski commented on app/src/main/res/navigation/nav_graph.xml
> +        android:id="@+id/login_fragment"
Also our discussion about naming convention in XMLs is still valid here, as you are refactoring most of the app in this PR 😉

2021-01-15 08:32 UTC, krzdabrowski commented on base/build.gradle
> +apply from: "$rootProject.projectDir/plugs.gradle"
As in one of my earlier comments, you don't need to repeat yourself with these `apply from` in each module 🙂 Same applies for `deps.gradle` and other modules.

2021-01-15 08:32 UTC, krzdabrowski commented on plugs.gradle
> +apply plugin: 'kotlin-android'
As I remember correctly, `apply plugin` will be deprecated soon. Consider refactor to `plugins {}` syntax.

2021-01-15 08:32 UTC, krzdabrowski commented on base/build.gradle
> +        jvmTarget = '1.8'
It's a minor but I personally like to set it to `JavaVersion.VERSION_1_8` for consistency and to prevent magic numbers 🙂

2021-01-15 08:32 UTC, krzdabrowski commented on base/build.gradle
> +dependencies {
Empty block?

2021-01-15 08:32 UTC, krzdabrowski commented on user/src/main/res/layout/fragment_main.xml
> +        app:layout_constraintTop_toTopOf="parent"
🙂

2021-01-15 08:54 UTC, braczkow commented on app/src/main/java/com/example/appName/nav/NavigationModule.kt
> +@InstallIn(FragmentComponent::class)
Why not?
Note that navController is scoped to Activity, thus: each Fragment gets its own NavigationImpl, all use the same navController

```
2021-01-15 09:51:21.914 9739-9739/com.example D/NAV: NavigationModule init of com.example.appName.nav.NavigationModule@35ed5ae
2021-01-15 09:51:21.917 9739-9739/com.example D/NAV: NavigationImpl init of com.example.appName.nav.NavigationImpl@7102f4f, navController: androidx.navigation.NavHostController@66866dc
2021-01-15 09:51:21.998 9739-9739/com.example D/NAV: LoginFragment navigation: com.example.appName.nav.NavigationImpl@7102f4f


2021-01-15 09:51:31.374 9739-9739/com.example D/NAV: NavigationModule init of com.example.appName.nav.NavigationModule@16416cf
2021-01-15 09:51:31.374 9739-9739/com.example D/NAV: NavigationImpl init of com.example.appName.nav.NavigationImpl@9aaf85c, navController: androidx.navigation.NavHostController@66866dc
2021-01-15 09:51:31.389 9739-9739/com.example D/NAV: HomeFragment navigation: com.example.appName.nav.NavigationImpl@9aaf85c
```

navController: androidx.navigation.NavHostController@66866dc

2021-01-15 08:55 UTC, braczkow commented on app/build.gradle
>      debugImplementation "com.facebook.stetho:stetho:${versions.stetho}"
Because it's specific to app module - there is no need for base/feature to know about it

2021-01-15 08:57 UTC, braczkow commented on base/src/main/java/com/example/base/nav/Navigation.kt
> +        data class toHomeScreen(val text: String): Direction()
Well, sure, but anything related to Home feature is just a showcase and will be replaced by a real feature soon.

2021-01-15 08:59 UTC, braczkow commented on app/src/main/java/com/example/appName/nav/NavigationModule.kt
> +@InstallIn(FragmentComponent::class)
See _debug/navigation-logs_ for a reference

2021-01-15 09:02 UTC, braczkow commented on app/src/main/res/layout/activity_main.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
On one hand: sure, on the other: it makes clear that you can add some Activity-level UI

2021-01-15 09:16 UTC, krzdabrowski commented on app/src/main/java/com/example/appName/nav/NavigationModule.kt
> +@InstallIn(FragmentComponent::class)
If NavController is Activity-tied, that's fine. Personally I would prefer `ActivityComponent` for all to avoid creation new objects, but up to you 🙂

2021-01-15 09:42 UTC, braczkow commented on app/src/main/java/com/example/appName/nav/NavigationModule.kt
> +@InstallIn(FragmentComponent::class)
Anyway, thanks to your comment I have found one nasty bug 👍

2021-01-18 09:32 UTC, braczkow commented on base/build.gradle
> +        jvmTarget = '1.8'
done

2021-01-18 09:48 UTC, MDikkii requested changes

2021-01-18 09:48 UTC, MDikkii commented on app/src/main/java/com/example/appName/nav/NavigationModule.kt
> +import javax.inject.Provider
Not used imports

2021-01-18 09:48 UTC, MDikkii commented on base/src/main/java/com/example/base/presentation/BaseFragment.kt
> +import dagger.Lazy
Unused imports

2021-01-18 09:48 UTC, MDikkii commented on home/src/main/java/com/example/home/HomeFragment.kt
> +        home_text.text = arguments?.getString(TEXT_ARG)
`home_text` still as snake case

2021-01-18 09:48 UTC, MDikkii commented on user/src/main/java/com/example/user/di/MainModule.kt
> +    fun provideInitialMainViewState(): LoginViewState = LoginViewState()
Please change class and provide names as well

2021-01-18 09:48 UTC, MDikkii commented on user/src/main/java/com/example/user/presentation/LoginPresenter.kt
> +            return Flowable.empty()
I don't know if it won't be more readable to make `publishEvent` calls in reduce phase

2021-01-18 09:48 UTC, MDikkii commented on user/src/main/res/layout/fragment_login.xml
> +        />
👀

2021-01-18 09:54 UTC, braczkow commented on base/src/main/java/com/example/base/presentation/BaseFragment.kt
> +import dagger.Lazy
done

2021-01-18 09:54 UTC, braczkow commented on user/src/main/java/com/example/user/di/MainModule.kt
> +    fun provideInitialMainViewState(): LoginViewState = LoginViewState()
done

2021-01-18 09:54 UTC, braczkow commented on home/src/main/java/com/example/home/HomeFragment.kt
> +        home_text.text = arguments?.getString(TEXT_ARG)
XML-originating names are not yet aligned

2021-01-18 09:59 UTC, braczkow commented on user/src/main/java/com/example/user/presentation/LoginPresenter.kt
> +            return Flowable.empty()
I don't have strict feelings about this, both ways seem fine for me, at least in current implementation. IMO it would be nice to break the constraint that acceptIntent has to provide a PartialChange. But it's a much bigger change. :)

2021-01-18 10:02 UTC, braczkow commented on user/src/main/res/layout/fragment_login.xml
> +        />
?

2021-01-18 10:02 UTC, braczkow commented on app/src/main/java/com/example/appName/nav/NavigationModule.kt
> +import javax.inject.Provider
done

2021-01-18 10:02 UTC, braczkow commented on base/build.gradle
> +dependencies {
Fixed

2021-01-18 10:04 UTC, braczkow commented on base/build.gradle
> +apply from: "$rootProject.projectDir/plugs.gradle"
I have extracted a common lib.gradle, that has all the benefits: does not pollute root build.gradle and prevents from applying deps.gradle in all the gradles

2021-01-18 10:08 UTC, braczkow commented on app/src/main/res/layout/activity_main.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
Fixed

2021-01-18 10:08 UTC, braczkow commented on app/src/main/java/com/example/appName/nav/NavigationModule.kt
> +@InstallIn(FragmentComponent::class)
After big discussion on Friday: closing, as it solved.

2021-01-18 10:11 UTC, braczkow commented on app/build.gradle
> +    implementation project(path: ':base')
Sure. But AS generates it this way. Changing it to project(':base') will either: make future developer introduce inconsistency (by leaving what AS generated), or make her/him think about such a detail.

2021-01-18 10:13 UTC, braczkow commented on base/src/main/java/com/example/base/nav/Navigation.kt
> +        data class toHomeScreen(val text: String): Direction()
@przemek19980102 @krzdabrowski could you please answer? :)

2021-01-18 10:15 UTC, braczkow commented on user/src/main/res/layout/fragment_login.xml
> +        />
Fixed

2021-01-18 10:26 UTC, braczkow commented on base/src/main/java/com/example/base/nav/Navigation.kt
> +        data class toHomeScreen(val text: String): Direction()
Ok, I've aligned it with your comment

2021-01-18 10:38 UTC, MDikkii commented on user/src/main/java/com/example/user/presentation/LoginPresenter.kt
> +            return Flowable.empty()
Yep... Like... Moving away from MVI :D

2021-01-18 10:49 UTC, krzdabrowski approved these changes

2021-01-18 11:07 UTC, merged