Feature/plop template
codequest-eu/devstarter-android-mvi pull request #25
Opened 2021-01-21 09:36 UTC by braczkow

2021-01-21 11:15 UTC, MDikkii requested changes

2021-01-21 11:15 UTC, MDikkii commented on README.md
> +Templates solution was developerd with help of node.js [plop](https://plopjs.com/) module: .
typo `developerd`

2021-01-21 11:15 UTC, MDikkii commented on .plop-templates/mvi/{{pascalCase name}}ViewState.kt.hbs
> +}
Missing new line

2021-01-21 13:18 UTC, braczkow commented on README.md
> +Templates solution was developerd with help of node.js [plop](https://plopjs.com/) module: .
Fixed

2021-01-21 13:18 UTC, braczkow commented on .plop-templates/mvi/{{pascalCase name}}ViewState.kt.hbs
> +}
Fixed

2021-01-22 09:55 UTC, MDikkii approved these changes

2021-01-22 09:55 UTC, merged