Feature/backend integration
codequest-eu/devstarter-android-mvi pull request #34
Opened 2021-02-12 13:37 UTC by braczkow

do not merge

2021-03-05 13:19 UTC, krzdabrowski reviewed
I would definitely refactor code in some (most) files - many unnecessary empty lines, some weird formatting here and there.

Also, I would suggest someone else who is more knowledgeable with DevStarter to take a look on logic implementation part 🙂

2021-03-05 13:19 UTC, krzdabrowski commented on base/src/main/java/com/example/base/network/NetworkModule.kt
> +        const val CONTENTTYPE_INTERCEPTOR_NAME = "CONTENTTYPE_INTERCEPTOR_NAME"
Is it possible to use these consts somewhere else? If no, maybe change to `private` 🙂

2021-03-05 13:19 UTC, krzdabrowski commented on gradles/deps.gradle
> +    implementation("com.squareup.moshi:moshi:${versions.moshi}")
Is it justified here to use `()` brackets instead of standard Groovy syntax?

2021-03-05 13:19 UTC, krzdabrowski commented on user/src/main/java/com/example/user/auth/model/register/RegisterReq.kt
> +        const val ATTRIBUTE_EMIAL = "email"
typo 🙂

2021-03-05 13:19 UTC, krzdabrowski commented on user/src/main/java/com/example/user/auth/usecase/RegisterUseCase.kt
> +                    if (tokens != null) {
Possible simplification with `.let`?

2021-03-05 13:19 UTC, krzdabrowski commented on user/src/main/java/com/example/user/data/LocalUserRepository.kt
> +    override fun getUser(): Single<com.example.user.model.User> {
Could be imported better

2021-03-05 13:19 UTC, krzdabrowski commented on user/src/main/java/com/example/user/data/UserRepository.kt
> +    fun getUser(): Single<com.example.user.model.User>
Same applies here

2021-03-05 15:19 UTC, kubak89 requested changes

2021-03-05 15:19 UTC, kubak89 commented on user/src/main/java/com/example/user/auth/di/AuthModule.kt
> +    fun provideAuthenticator(impl: UserAuthenticator): Authenticator = impl
Nice one, haven't thought of this way of providing interface implementations myself before 👍

2021-03-05 15:19 UTC, kubak89 commented on user/src/main/java/com/example/user/auth/model/register/RegisterReq.kt
> +data class RegisterReq(
Nit: as before, I think that we may be better off with a full name.

2021-03-05 15:19 UTC, kubak89 commented on user/src/main/java/com/example/user/auth/model/register/RegisterResp.kt
> +internal data class RegisterResp(
As before - `RegisterResponse` is more readable and easier to pronounce.

2021-03-05 15:19 UTC, kubak89 commented on user/src/main/java/com/example/user/auth/usecase/LoginUseCase.kt
> +}
Nit, but I think we might not be needing a separate interface for every use case in our application.

2021-03-05 15:19 UTC, kubak89 commented on user/src/main/java/com/example/user/presentation/login/LoginPresenter.kt
> +        private val exampleUserRepository: UserRepository
In case we are using use cases - shouldn't twe also use an use case for fetching the user?

2021-03-05 15:19 UTC, kubak89 commented on user/src/main/java/com/example/user/presentation/register/RegisterIntent.kt
> +    object GoBack: RegisterIntent()
I think that navigation actions that don't cause backend interactions should be handled on a view side.

2021-03-05 15:19 UTC, kubak89 commented on user/src/main/java/com/example/user/presentation/register/RegisterMviView.kt
> +            acceptIntent(RegisterIntent.GoBack)
Couldn't we just handle the navigation here?

2021-03-05 15:19 UTC, kubak89 commented on user/src/main/java/com/example/user/presentation/register/RegisterViewEvent.kt
> +    object GoBack: RegisterViewEvent()
As mentioned before: I don't think that's necessary.

2021-03-05 15:51 UTC, braczkow commented on user/src/main/java/com/example/user/auth/data/RefreshTokenApi.kt
> +}
Dummy one for later use.

2021-03-05 15:53 UTC, braczkow commented on gradles/deps.gradle
> +    implementation("com.squareup.moshi:moshi:${versions.moshi}")
I believe `()` is a standard Groovy syntax, but it's a nice catch and I'll align with the rest of the code. :)

2021-03-05 16:10 UTC, braczkow commented on user/src/main/java/com/example/user/data/LocalUserRepository.kt
> +    override fun getUser(): Single<com.example.user.model.User> {
fixed

2021-03-05 16:10 UTC, braczkow commented on user/src/main/java/com/example/user/data/UserRepository.kt
> +    fun getUser(): Single<com.example.user.model.User>
fixed

2021-03-05 16:10 UTC, braczkow commented on user/src/main/java/com/example/user/auth/usecase/RegisterUseCase.kt
> +                    if (tokens != null) {
fixed

2021-03-05 16:10 UTC, braczkow commented on user/src/main/java/com/example/user/auth/model/register/RegisterReq.kt
> +        const val ATTRIBUTE_EMIAL = "email"
fixed

2021-03-09 14:07 UTC, braczkow commented on base/src/main/java/com/example/base/network/Data.kt
> +)
This will be handled in a next PR

2021-03-09 14:11 UTC, braczkow commented on user/src/main/java/com/example/user/presentation/register/RegisterMviView.kt
> +            acceptIntent(RegisterIntent.GoBack)
I agree that it's overcomplicated to handle this via ViewModel, but I don't think it's (Mvi)View responsibility to handle any kind of Navigation, it already handles render/intent. For me it should be handled in a Fragment, but that requires a little more flexibility with `acceptIntent` approach

2021-03-09 14:13 UTC, braczkow commented on base/src/main/java/com/example/base/network/NetworkModule.kt
> +    )
Well, originally I thought that there will be more `Interceptors` to take care of, hence the approach. I'll change that

2021-03-10 10:04 UTC, braczkow commented on user/src/main/java/com/example/user/auth/usecase/LoginUseCase.kt
> +}
In case `RegisterUseCase` would be already an implementation,  you would have to a) mark it `open`, b) provide dependencies for its ctor. If you think it's a better approach: I'm fine with it and will refactor

2021-03-10 10:06 UTC, braczkow commented on user/src/main/java/com/example/user/auth/usecase/LoginUseCase.kt
> +}
One more:
if you want to make an `UseCase` available for other modules, it cannot be `internal`. And `RegisterUseCase` does have `internal` dependencies, so that would be a blocker.

2021-03-10 10:33 UTC, braczkow commented on base/src/main/java/com/example/base/network/NetworkModule.kt
> +        const val CONTENTTYPE_INTERCEPTOR_NAME = "CONTENTTYPE_INTERCEPTOR_NAME"
`base.network` has been significantly refactored. Yet this is a const for Named-injection, I think it belongs to the `Module` class

2021-03-10 10:35 UTC, braczkow commented on base/src/main/java/com/example/base/network/NetworkModule.kt
> +    )
Fixed

2021-03-10 10:41 UTC, braczkow commented on gradles/config.gradle
> +            logIntercept : '4.9.0',
Fixed

2021-03-12 14:41 UTC, braczkow commented on user/src/main/java/com/example/user/presentation/login/LoginPresenter.kt
> +        private val exampleUserRepository: UserRepository
done

2021-03-12 14:58 UTC, braczkow commented on user/src/main/java/com/example/user/presentation/register/RegisterIntent.kt
> +    object GoBack: RegisterIntent()
Answer below

2021-03-12 14:58 UTC, braczkow commented on user/src/main/java/com/example/user/presentation/register/RegisterViewEvent.kt
> +    object GoBack: RegisterViewEvent()
Answer above

2021-07-30 09:59 UTC, Ant8 commented on base/src/main/java/com/example/base/network/model/Relationship.kt
> +data class Relationship(
what's the use for this class? relationships are generally handled by json-api. Can't see it used anywhere

2021-07-30 09:59 UTC, Ant8 commented on base/src/main/java/com/example/base/network/RetrofitFactory.kt
> +interface RetrofitFactory {
what's the use for this, isn't it redundant?

2021-07-30 09:59 UTC, Ant8 commented on user/src/main/java/com/example/user/auth/Consts.kt
> +    const val AUTHORIZATION_HEADER_KEY = "Authorization"
nit - why in `user/auth` package, and not `network`?

2021-07-30 09:59 UTC, Ant8 commented on user/src/main/java/com/example/user/auth/model/register/RegisterRequest.kt
> +                data = Data(
wtf

2021-07-30 12:09 UTC, MDikkii approved these changes

2021-07-30 12:09 UTC, MDikkii commented on user/src/main/java/com/example/user/auth/Consts.kt
> +    const val AUTHORIZATION_HEADER_KEY = "Authorization"
It is not used outside the `auth` module for now. I agree that maybe we will need it also for other backend calls. I would vote to change it when we add more integration with devstarter backend. What do you think?

2021-08-06 09:01 UTC, krzdabrowski approved these changes

2021-08-06 09:03 UTC, merged