Refactor/modular navigation
codequest-eu/devstarter-android-mvi pull request #35
Opened 2021-02-12 15:57 UTC by kubak89

2021-02-12 16:20 UTC, Ant8 reviewed
left a few questions. Overall, lgtm

2021-02-12 16:20 UTC, Ant8 commented on app/build.gradle
> +    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.4.30"
is it needed? apparently stdlib is added automagically

2021-02-12 16:20 UTC, Ant8 commented on build.gradle
> +        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:2.3.3"
:+1:

2021-02-12 16:20 UTC, Ant8 commented on gradles/plugs.gradle
> +apply plugin: "androidx.navigation.safeargs.kotlin"
:+1:

2021-02-12 16:20 UTC, Ant8 commented on user/src/main/java/com/example/user/presentation/register/RegisterFragment.kt
> +        view.findViewById<Button>(R.id.destination_go_back_button)
no view binding?

2021-02-12 16:20 UTC, Ant8 commented on base/src/main/res/values/strings.xml
> -    <string name="action_login">Login</string>
:+1:

2021-02-12 16:20 UTC, Ant8 commented on app/src/main/res/navigation/nav_graph.xml
>      <fragment
no separate `nav_graph` for home? is `home_fragment` always reachable?

2021-02-12 16:20 UTC, Ant8 commented on user/src/main/res/navigation/user_nav_graph.xml
> +        android:id="@+id/mock_destination_fragment"
why not `registration_fragment`?

2021-02-15 09:07 UTC, braczkow requested changes

2021-02-15 09:07 UTC, braczkow commented on base/src/main/java/com/example/base/nav/Navigation.kt
> +    fun navigate(direction: NavDirections)
By this change you couple our internal navigation logic to the library, which we/I wanted to avoid by all means.

2021-02-15 09:07 UTC, braczkow commented on user/src/main/java/com/example/user/presentation/login/LoginFragment.kt
> +            navigation.navigate(LoginFragmentDirections.actionLoginFragmentToMockDestinationFragment())
Nit, but even in a 'demo' code it makes you think twice: please keep the naming consistent ('mock' vs 'register' names)

2021-02-15 09:07 UTC, braczkow commented on user/src/main/java/com/example/user/presentation/login/LoginPresenter.kt
> +            publishEvent(LoginViewEvent.LoginSuccess)
<3

2021-02-19 08:47 UTC, kubak89 commented on app/src/main/res/navigation/nav_graph.xml
>      <fragment
Home module consists of one empty fragment so far, so I didn't add a separate nav graph for now.

2021-02-19 08:49 UTC, kubak89 commented on base/src/main/java/com/example/base/nav/Navigation.kt
> +    fun navigate(direction: NavDirections)
Why do we want that? I feel like your solution created a lot of boilerplate without any advantages - at least none I was able to see.

2021-02-19 08:50 UTC, kubak89 commented on user/src/main/java/com/example/user/presentation/register/RegisterFragment.kt
> +        view.findViewById<Button>(R.id.destination_go_back_button)
Yes, it's a dummy destination, at least for now.

2021-02-19 08:50 UTC, kubak89 commented on user/src/main/res/navigation/user_nav_graph.xml
> +        android:id="@+id/mock_destination_fragment"
Forgot to rename it after I have renamed the fragment.

2021-02-19 08:53 UTC, kubak89 commented on user/src/main/java/com/example/user/presentation/login/LoginFragment.kt
> +            navigation.navigate(LoginFragmentDirections.actionLoginFragmentToMockDestinationFragment())
Yes, I forgot to rename that action after I renamed the fragment.

2021-02-19 09:16 UTC, krzdabrowski commented on app/src/main/java/com/example/appName/EntryPointFragment.kt
> +                              savedInstanceState: Bundle?): View? {
Some weird code formatting

2021-02-19 09:16 UTC, krzdabrowski commented on app/src/main/java/com/example/appName/EntryPointFragment.kt
> +        (requireActivity() as MainActivity).navController.navigate(EntryPointFragmentDirections.actionEntryPointFragmentToUserNavGraph())
Maybe extract to more chain-like formatting (multiline)? 🙂

2021-02-19 09:16 UTC, krzdabrowski commented on user/src/main/java/com/example/user/presentation/register/RegisterFragment.kt
> +class RegisterFragment : Fragment(R.layout.fragment_register) {
It purposely doesn't inherit from `BaseFragment`? 🙂

2021-02-19 09:26 UTC, kubak89 commented on user/src/main/java/com/example/user/presentation/register/RegisterFragment.kt
> +class RegisterFragment : Fragment(R.layout.fragment_register) {
Yes, at this moment it's only a dummy destination. It will be implemented later. I added the name, so we won't have to change navigation graph when implementing this.

2021-02-19 09:51 UTC, kubak89 commented on app/src/main/java/com/example/appName/EntryPointFragment.kt
> +                              savedInstanceState: Bundle?): View? {
Fixed it, and added ktlint to check for such problems.

2021-02-19 09:51 UTC, kubak89 commented on app/src/main/java/com/example/appName/EntryPointFragment.kt
> +        (requireActivity() as MainActivity).navController.navigate(EntryPointFragmentDirections.actionEntryPointFragmentToUserNavGraph())
Changed.

2021-02-19 09:55 UTC, krzdabrowski approved these changes

2021-02-26 11:18 UTC, braczkow approved these changes

2021-02-26 11:46 UTC, merged