Add moshi-jsonapi
codequest-eu/devstarter-android-mvi pull request #36
Opened 2021-03-15 10:52 UTC by braczkow

Probably my last input :(

Added `moshi-jsonapi`, added `assertJ`

Works fine.

2021-07-23 11:05 UTC, MDikkii requested changes

2021-07-23 14:14 UTC, MDikkii approved these changes

2021-07-30 09:53 UTC, krzdabrowski approved these changes

2021-08-06 09:05 UTC, Ant8 approved these changes
generally LGTM

2021-08-06 09:05 UTC, Ant8 commented on user/src/main/java/com/example/user/auth/data/dto/SessionDto.kt
> +    @field:Json(name = "access_token") val access_token: String = "",
nit, I'd change fields names to snake case

2021-08-06 09:05 UTC, Ant8 commented on base/src/main/java/com/example/base/testutils/TestUtils.kt
> +        clazzes.forEach {
huh, this together with `@Provide into set` is quite clever, although perhaps not that readable at first sight

2021-08-06 09:05 UTC, Ant8 commented on user/src/test/java/com/example/user/auth/data/dto/AccountDtoTest.kt
> +class AccountDtoTest {
:open_mouth:

2021-08-06 19:40 UTC, MDikkii commented on user/src/main/java/com/example/user/auth/data/dto/SessionDto.kt
> +    @field:Json(name = "access_token") val access_token: String = "",
Done

2021-08-06 19:40 UTC, merged